apiVersion: v1
kind: Service
metadata:
  name: home-service
spec:
  type: NodePort
  selector:
    app: web-home
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: detail-service
spec:
  type: NodePort
  selector:
    app: web-detail
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: page-service
spec:
  type: NodePort
  selector:
    app: web-page
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-home
  labels:
    app: deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-home
      type: deploy
  template:
    metadata:
      labels:
        app: web-home
        type: deploy
        version: "v1.2"
    spec:
      containers:
      - name: web-home
        image: minjun5876/home:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-detail
  labels:
    app: deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-detail
      type: deploy
  template:
    metadata:
      labels:
        app: web-detail
        type: deploy
        version: "v1.2"
    spec:
      containers:
      - name: web-detail
        image: minjun5876/detail:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-page
  labels:
    app: deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-page
      type: deploy
  template:
    metadata:
      labels:
        app: web-page
        type: deploy
        version: "v1.2"
    spec:
      containers:
      - name: web-page
        image: minjun5876/page:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-pull-secret
